import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <nav>
          <h1>Logo</h1>
          <li>
            <a href="/">Start</a>
          </li>
          <li>
            <a href="about">About</a>
          </li>
        </nav>
        {children}
      </body>
    </html>
  );
}
